# Import Library & CSV

In [1]:
import pandas as pd
dataset= pd.read_csv("Building_Energy_Efficiency.csv")
dataset

,Building_ID,Relative_Compactness,Building_Type,Surface_Area_m2,Wall_Area_m2,Roof_Area_m2,Overall_Height_m,Orientation,Glazing_Area_ratio,Glazing_Distribution,Heating_Load_kWh,Cooling_Load_kWh
0,BLD-0001,0.98,High_Rise,514.5,294.0,110.25,7.0,North,0.0,NaN,15.55,21.33
1,BLD-0002,0.98,High_Rise,514.5,294.0,110.25,7.0,East,0.0,NaN,15.55,21.33
2,BLD-0003,0.98,High_Rise,514.5,294.0,110.25,7.0,South,0.0,NaN,15.55,21.33
3,BLD-0004,0.98,High_Rise,514.5,NaN,110.25,7.0,West,0.0,NaN,NaN,21.33
4,BLD-0005,0.90,High_Rise,563.5,318.5,122.50,7.0,NaN,0.0,NaN,20.84,28.28
...,...,...,...,...,...,...,...,...,...,...,...,...
763,BLD-0764,0.64,Low_Rise,784.0,343.0,220.50,3.5,West,0.4,West_Heavy,17.88,21.40
764,BLD-0765,0.62,Low_Rise,808.5,367.5,220.50,3.5,North,0.4,NaN,16.54,16.88
765,BLD-0766,0.62,Low_Rise,808.5,367.5,220.50,3.5,East,0.4,West_Heavy,16.44,17.11
766,BLD-0767,0.62,Low_Rise,808.5,367.5,220.50,3.5,South,0.4,West_Heavy,16.48,16.61
767,BLD-0768,0.62,Low_Rise,808.5,367.5,220.50,3.5,West,0.4,West_Heavy,16.64,16.03

# Check No. of columns& Rows

In [2]:
# Check shape (rows, columns)
dataset.shape
print(dataset.shape)

(768, 12)

In [3]:
# Column names
dataset.columns
print(dataset.columns)

Index(['Building_ID', 'Relative_Compactness', 'Building_Type',
       'Surface_Area_m2', 'Wall_Area_m2', 'Roof_Area_m2', 'Overall_Height_m',
       'Orientation', 'Glazing_Area_ratio', 'Glazing_Distribution',
       'Heating_Load_kWh', 'Cooling_Load_kWh'],
      dtype='object')

In [4]:
# Data types
dataset.dtypes
print(dataset.dtypes)

Building_ID              object
Relative_Compactness    float64
Building_Type            object
Surface_Area_m2         float64
Wall_Area_m2            float64
Roof_Area_m2            float64
Overall_Height_m        float64
Orientation              object
Glazing_Area_ratio      float64
Glazing_Distribution     object
Heating_Load_kWh        float64
Cooling_Load_kWh        float64
dtype: object

In [5]:
# Basic statistics
dataset.describe()
print(dataset.describe)

<bound method NDFrame.describe of     Building_ID  Relative_Compactness Building_Type  Surface_Area_m2  \
0      BLD-0001                  0.98     High_Rise            514.5
1      BLD-0002                  0.98     High_Rise            514.5
2      BLD-0003                  0.98     High_Rise            514.5
3      BLD-0004                  0.98     High_Rise            514.5
4      BLD-0005                  0.90     High_Rise            563.5
..          ...                   ...           ...              ...
763    BLD-0764                  0.64      Low_Rise            784.0
764    BLD-0765                  0.62      Low_Rise            808.5
765    BLD-0766                  0.62      Low_Rise            808.5
766    BLD-0767                  0.62      Low_Rise            808.5
767    BLD-0768                  0.62      Low_Rise            808.5

     Wall_Area_m2  Roof_Area_m2  Overall_Height_m Orientation  \
0           294.0        110.25               7.0       North
1           294.0        110.25               7.0        East
2           294.0        110.25               7.0       South
3             NaN        110.25               7.0        West
4           318.5        122.50               7.0         NaN
..            ...           ...               ...         ...
763         343.0        220.50               3.5        West
764         367.5        220.50               3.5       North
765         367.5        220.50               3.5        East
766         367.5        220.50               3.5       South
767         367.5        220.50               3.5        West

     Glazing_Area_ratio Glazing_Distribution  Heating_Load_kWh  \
0                   0.0                  NaN             15.55
1                   0.0                  NaN             15.55
2                   0.0                  NaN             15.55
3                   0.0                  NaN               NaN
4                   0.0                  NaN             20.84
..                  ...                  ...               ...
763                 0.4           West_Heavy             17.88
764                 0.4                  NaN             16.54
765                 0.4           West_Heavy             16.44
766                 0.4           West_Heavy             16.48
767                 0.4           West_Heavy             16.64

     Cooling_Load_kWh
0               21.33
1               21.33
2               21.33
3               21.33
4               28.28
..                ...
763             21.40
764             16.88
765             17.11
766             16.61
767             16.03

[768 rows x 12 columns]>

# Check Missing Values

In [6]:
dataset.isnull().sum()

Building_ID               0
Relative_Compactness     38
Building_Type             0
Surface_Area_m2          30
Wall_Area_m2             46
Roof_Area_m2             38
Overall_Height_m         23
Orientation              53
Glazing_Area_ratio       61
Glazing_Distribution    112
Heating_Load_kWh         30
Cooling_Load_kWh         30
dtype: int64

# Split Qualitative and Quantitative columns

In [9]:
def quanQual(dataset):
        quan=[]
        qual=[]
        for columnName in dataset.columns:
            #print(columnName)
            if(dataset[columnName].dtype=='O'):
                #print("qual")
                qual.append(columnName)
            else:
                #print("quan")
                quan.append(columnName)
        return quan,qual

In [10]:
quan,qual=quanQual(dataset)

In [11]:
dataset[quan]

,Relative_Compactness,Surface_Area_m2,Wall_Area_m2,Roof_Area_m2,Overall_Height_m,Glazing_Area_ratio,Heating_Load_kWh,Cooling_Load_kWh
0,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,0.0,15.55,21.33
3,0.98,514.5,NaN,110.25,7.0,0.0,NaN,21.33
4,0.90,563.5,318.5,122.50,7.0,0.0,20.84,28.28
...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,0.4,17.88,21.40
764,0.62,808.5,367.5,220.50,3.5,0.4,16.54,16.88
765,0.62,808.5,367.5,220.50,3.5,0.4,16.44,17.11
766,0.62,808.5,367.5,220.50,3.5,0.4,16.48,16.61
767,0.62,808.5,367.5,220.50,3.5,0.4,16.64,16.03

In [12]:
dataset[qual]

    Building_ID Building_Type Orientation Glazing_Distribution
0      BLD-0001     High_Rise       North                  NaN
1      BLD-0002     High_Rise        East                  NaN
2      BLD-0003     High_Rise       South                  NaN
3      BLD-0004     High_Rise        West                  NaN
4      BLD-0005     High_Rise         NaN                  NaN
..          ...           ...         ...                  ...
763    BLD-0764      Low_Rise        West           West_Heavy
764    BLD-0765      Low_Rise       North                  NaN
765    BLD-0766      Low_Rise        East           West_Heavy
766    BLD-0767      Low_Rise       South           West_Heavy
767    BLD-0768      Low_Rise        West           West_Heavy

[768 rows x 4 columns]

# Fill missing values with median (numerical columns)

In [14]:
import numpy as np
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy="median")
dataset[quan] = imputer.fit_transform(dataset[quan])

In [16]:
dataset[quan]

,Relative_Compactness,Surface_Area_m2,Wall_Area_m2,Roof_Area_m2,Overall_Height_m,Glazing_Area_ratio,Heating_Load_kWh,Cooling_Load_kWh
0,0.98,514.5,294.000000,110.25,7.0,0.0,15.550000,21.33
1,0.98,514.5,294.000000,110.25,7.0,0.0,15.550000,21.33
2,0.98,514.5,294.000000,110.25,7.0,0.0,15.550000,21.33
3,0.98,514.5,318.975069,110.25,7.0,0.0,22.448084,21.33
4,0.90,563.5,318.500000,122.50,7.0,0.0,20.840000,28.28
...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.000000,220.50,3.5,0.4,17.880000,21.40
764,0.62,808.5,367.500000,220.50,3.5,0.4,16.540000,16.88
765,0.62,808.5,367.500000,220.50,3.5,0.4,16.440000,17.11
766,0.62,808.5,367.500000,220.50,3.5,0.4,16.480000,16.61
767,0.62,808.5,367.500000,220.50,3.5,0.4,16.640000,16.03

In [19]:
# Fill missing values with median (numerical columns)
dataset[quan].isnull().sum()

Relative_Compactness    0
Surface_Area_m2         0
Wall_Area_m2            0
Roof_Area_m2            0
Overall_Height_m        0
Glazing_Area_ratio      0
Heating_Load_kWh        0
Cooling_Load_kWh        0
dtype: int64

In [20]:
#no null values

# Fill missing values with median (categorical columns)

In [21]:
# Fill nominal columns with mode
dataset['Building_Type'] = dataset['Building_Type'].fillna(
    dataset['Building_Type'].mode()[0]
)

dataset['Orientation'] = dataset['Orientation'].fillna(
    dataset['Orientation'].mode()[0]
)

In [25]:
#Ordinal Column with mode
dataset['Glazing_Distribution'] = dataset['Glazing_Distribution'].fillna(
    dataset['Glazing_Distribution'].mode()[0]
)

In [26]:
dataset[qual]

    Building_ID Building_Type Orientation Glazing_Distribution
0      BLD-0001     High_Rise       North           East_Heavy
1      BLD-0002     High_Rise        East           East_Heavy
2      BLD-0003     High_Rise       South           East_Heavy
3      BLD-0004     High_Rise        West           East_Heavy
4      BLD-0005     High_Rise        West           East_Heavy
..          ...           ...         ...                  ...
763    BLD-0764      Low_Rise        West           West_Heavy
764    BLD-0765      Low_Rise       North           East_Heavy
765    BLD-0766      Low_Rise        East           West_Heavy
766    BLD-0767      Low_Rise       South           West_Heavy
767    BLD-0768      Low_Rise        West           West_Heavy

[768 rows x 4 columns]

In [27]:
dataset[qual].isnull().sum()

Building_ID             0
Building_Type           0
Orientation             0
Glazing_Distribution    0
dtype: int64

In [28]:
#no null values

In [29]:
dataset

,Building_ID,Relative_Compactness,Building_Type,Surface_Area_m2,Wall_Area_m2,Roof_Area_m2,Overall_Height_m,Orientation,Glazing_Area_ratio,Glazing_Distribution,Heating_Load_kWh,Cooling_Load_kWh
0,BLD-0001,0.98,High_Rise,514.5,294.000000,110.25,7.0,North,0.0,East_Heavy,15.550000,21.33
1,BLD-0002,0.98,High_Rise,514.5,294.000000,110.25,7.0,East,0.0,East_Heavy,15.550000,21.33
2,BLD-0003,0.98,High_Rise,514.5,294.000000,110.25,7.0,South,0.0,East_Heavy,15.550000,21.33
3,BLD-0004,0.98,High_Rise,514.5,318.975069,110.25,7.0,West,0.0,East_Heavy,22.448084,21.33
4,BLD-0005,0.90,High_Rise,563.5,318.500000,122.50,7.0,West,0.0,East_Heavy,20.840000,28.28
...,...,...,...,...,...,...,...,...,...,...,...,...
763,BLD-0764,0.64,Low_Rise,784.0,343.000000,220.50,3.5,West,0.4,West_Heavy,17.880000,21.40
764,BLD-0765,0.62,Low_Rise,808.5,367.500000,220.50,3.5,North,0.4,East_Heavy,16.540000,16.88
765,BLD-0766,0.62,Low_Rise,808.5,367.500000,220.50,3.5,East,0.4,West_Heavy,16.440000,17.11
766,BLD-0767,0.62,Low_Rise,808.5,367.500000,220.50,3.5,South,0.4,West_Heavy,16.480000,16.61
767,BLD-0768,0.62,Low_Rise,808.5,367.500000,220.50,3.5,West,0.4,West_Heavy,16.640000,16.03

In [30]:
dataset.isnull().sum()

Building_ID             0
Relative_Compactness    0
Building_Type           0
Surface_Area_m2         0
Wall_Area_m2            0
Roof_Area_m2            0
Overall_Height_m        0
Orientation             0
Glazing_Area_ratio      0
Glazing_Distribution    0
Heating_Load_kWh        0
Cooling_Load_kWh        0
dtype: int64

In [31]:
#no overall null values

In [32]:
dataset.to_csv("Preprocessed_BuildingEnergy.csv",index=False)